"""
Utility functions for the demo application.
"""

from .demo_data import (
    init_demo_data,
    reset_demo_data,
    get_demo_user,
    get_demo_customer,
    seed_additional_users,
    seed_additional_products,
    seed_transactions,
    get_seed_statistics,
    create_predictable_test_data,
    export_demo_data,
    import_demo_data
)
from .templates import DEMO_PAGE_TEMPLATE
from .validators import (
    ValidationError,
    validate_email,
    validate_string,
    validate_integer,
    validate_float,
    check_sql_injection,
    check_xss,
    check_path_traversal,
    check_command_injection,
    sanitize_input,
    validate_required_fields,
    validate_json_request,
    validate_query_params
)
from .responses import (
    success_response,
    error_response,
    validation_error_response,
    not_found_response,
    unauthorized_response,
    forbidden_response,
    conflict_response,
    too_many_requests_response,
    internal_server_error_response,
    created_response,
    accepted_response,
    no_content_response,
    paginated_response,
    build_api_envelope
)
from .auth_helpers import (
    TokenError,
    generate_token,
    verify_token,
    generate_refresh_token,
    generate_api_key,
    hash_password,
    verify_password,
    extract_bearer_token,
    extract_api_key,
    require_auth,
    require_role,
    create_session,
    validate_session,
    invalidate_session,
    check_rate_limit,
    generate_mfa_secret,
    verify_totp_code
)
from .monitoring import (
    setup_logging,
    logger,
    log_request,
    track_performance,
    log_audit_event,
    log_security_event,
    log_exception,
    metrics,
    MetricsCollector,
    request_id_middleware
)

__all__ = [
    # Demo data
    'init_demo_data',
    'reset_demo_data',
    'get_demo_user',
    'get_demo_customer',
    'seed_additional_users',
    'seed_additional_products',
    'seed_transactions',
    'get_seed_statistics',
    'create_predictable_test_data',
    'export_demo_data',
    'import_demo_data',
    # Templates
    'DEMO_PAGE_TEMPLATE',
    # Validators
    'ValidationError',
    'validate_email',
    'validate_string',
    'validate_integer',
    'validate_float',
    'check_sql_injection',
    'check_xss',
    'check_path_traversal',
    'check_command_injection',
    'sanitize_input',
    'validate_required_fields',
    'validate_json_request',
    'validate_query_params',
    # Responses
    'success_response',
    'error_response',
    'validation_error_response',
    'not_found_response',
    'unauthorized_response',
    'forbidden_response',
    'conflict_response',
    'too_many_requests_response',
    'internal_server_error_response',
    'created_response',
    'accepted_response',
    'no_content_response',
    'paginated_response',
    'build_api_envelope',
    # Auth helpers
    'TokenError',
    'generate_token',
    'verify_token',
    'generate_refresh_token',
    'generate_api_key',
    'hash_password',
    'verify_password',
    'extract_bearer_token',
    'extract_api_key',
    'require_auth',
    'require_role',
    'create_session',
    'validate_session',
    'invalidate_session',
    'check_rate_limit',
    'generate_mfa_secret',
    'verify_totp_code',
    # Monitoring
    'setup_logging',
    'logger',
    'log_request',
    'track_performance',
    'log_audit_event',
    'log_security_event',
    'log_exception',
    'metrics',
    'MetricsCollector',
    'request_id_middleware'
]
