# Optimised container for Fargate (runs Gunicorn)
FROM python:3.12-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV PYTHONUNBUFFERED=1 \
    PORT=8080

WORKDIR /app

# Copy dependency files and install
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

# Copy application code
COPY . .

# Gunicorn provides better concurrency vs. flask dev server
CMD ["uv", "run", "gunicorn", "--bind", "0.0.0.0:8080", "--workers", "4", "--threads", "4", "app:app"]
