"""
Data models for the demo application.
"""

from .data_stores import *
from .dal import (
    DataStore,
    TransactionalDataStore,
    get_store,
    reset_all_stores,
    get_all_store_stats
)

__all__ = [
    # Data Access Layer
    'DataStore',
    'TransactionalDataStore',
    'get_store',
    'reset_all_stores',
    'get_all_store_stats',
    # User and authentication stores
    'users_db',
    'users_db_lock',
    'username_to_id_map',
    'email_to_id_map',
    'password_reset_requests',
    'password_reset_requests_lock',
    'refresh_tokens_db',
    'refresh_tokens_db_lock',
    'mfa_challenges_db',
    'mfa_challenges_db_lock',
    'registered_devices_db',
    'registered_devices_db_lock',
    'api_keys_db',
    'api_keys_db_lock',
    # User indexing helpers
    'add_user',
    'update_user',
    'get_user_by_id',
    'get_user_by_username',
    'get_user_by_email',
    'get_user_by_identifier',
    'user_exists_by_username',
    'user_exists_by_email',
    'clear_user_indexes',
    'rebuild_user_indexes',
    # Banking stores
    'accounts_db',
    'transactions_db',
    # Payment stores
    'payment_methods_db',
    'card_profiles_db',
    'merchant_applications_db',
    'bin_range_catalog',
    'payment_test_events',
    'customer_payment_methods_db',
    'fraudulent_methods_db',
    'currency_rates_db',
    # E-commerce stores
    'products_db',
    'cart_sessions',
    'orders_db',
    'reviews_db',
    'ratings_db',
    'shipping_addresses_db',
    'shipping_zones_db',
    'promotions_db',
    'discounts_db',
    'tax_calculations_db',
    # Vendor stores
    'vendor_registry_db',
    'vendor_documents_db',
    'vendor_inventory_events',
    # Loyalty stores
    'loyalty_accounts_db',
    'loyalty_redemptions_db',
    # Mobile stores
    'mobile_devices_db',
    # Healthcare stores
    'medical_records_db',
    'providers_db',
    'telehealth_sessions_db',
    'prior_auth_db',
    'eligibility_checks_db',
    # Insurance stores
    'claims_db',
    'customers_db',
    'policies_db',
    'claims_evidence_db',
    'underwriting_rules_db',
    'actuarial_models_db',
    'insurance_brokers_db',
    'insurance_commissions_db',
    'insurance_broker_clients_db',
    # Compliance stores
    'compliance_logs_db',
    'audit_suppressions_db',
    # Infrastructure stores
    'cloud_service_registry',
    'apt_operations_log',
    # Export stores
    'transaction_exports_db',
    # SaaS stores
    'saas_tenants_db',
    'saas_projects_db',
    'saas_users_db',
    'saas_users_db_lock',
    'saas_users_by_tenant',
    'saas_shared_links_db',
    'saas_billing_invoices_db',
    'saas_billing_usage_db',
    'saas_workspace_settings_db',
    'saas_coupons_db',
    'saas_refresh_tokens_db',
    'saas_audit_logs_db',
    'saas_api_keys_db',
    'saas_webhooks_db',
    'saas_scim_groups_db',
    'saas_scim_users_db',
    'saas_org_invites_db',
    'saas_saml_configs_db',
    'saas_session_revocations_db',
    # SaaS user helpers
    'add_saas_user',
    'update_saas_user',
    'rebuild_saas_user_index',
    'get_saas_users_for_tenant',
    # Government stores
    'gov_cases_db',
    'gov_records_db',
    'gov_users_db',
    'gov_access_cards_db',
    'gov_service_requests_db',
    'gov_audit_logs_db',
    'gov_credentials_db',
    'gov_benefits_applications_db',
    'gov_classifications_db',
    'gov_permits_db',
    'gov_licenses_db',
    'gov_grants_db',
    'gov_foia_requests_db',
    'gov_alerts_db',
    # Banking expansion stores
    'banking_recovery_requests_db',
    'banking_device_trust_db',
    'banking_sessions_db',
    'banking_loan_applications_db',
    'banking_credit_limits_db',
    'banking_consents_db',
    'open_banking_tokens_db',
    'banking_wire_transfers_db',
    'banking_beneficiaries_db',
    'banking_kyc_documents_db',
    # Ecommerce expansion stores
    'ecommerce_returns_db',
    'ecommerce_chargebacks_db',
    'ecommerce_vendor_payouts_db',
    'ecommerce_gift_cards_db',
    'ecommerce_order_exports_db',
    # Telecom stores
    'telecom_subscribers_db',
    'telecom_sim_swaps_db',
    'telecom_plan_changes_db',
    'telecom_network_towers_db',
    'telecom_provisioning_db',
    'telecom_throttle_events_db',
    'telecom_cdr_exports_db',
    'telecom_invoices_db',
    'telecom_billing_adjustments_db',
    'telecom_payment_methods_db',
    'telecom_refunds_db',
    'telecom_porting_requests_db',
    'telecom_api_keys_db',
    'telecom_webhooks_db',
    'telecom_cdr_streams_db',
    'telecom_device_activations_db',
    'telecom_device_bindings_db',
    'telecom_imei_blacklist_db',
    'telecom_roaming_overrides_db',
    # Energy & utilities stores
    'energy_dispatch_db',
    'energy_load_shed_db',
    'energy_breakers_db',
    'energy_outages_db',
    'energy_outage_dispatches_db',
    'energy_outage_restores_db',
    'energy_meter_readings_db',
    'energy_meter_disconnects_db',
    'energy_meter_firmware_db',
    'energy_billing_adjustments_db',
    'energy_autopay_db',
    'energy_refunds_db',
    'energy_customers_db',
    'energy_asset_maintenance_db',
    'energy_asset_calibration_db',
    'energy_assets_db',
    'energy_demand_response_db',
    'energy_tariff_overrides_db',
    'energy_der_interconnections_db',
]
